# Generated by Django 4.2.19 on 2025-07-28 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orchard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('state', models.CharField(choices=[('optimal', 'Óptima'), ('warning', 'Baja'), ('critical', 'Crítica')], max_length=10)),
                ('message_state', models.CharField(max_length=50)),
                ('orchard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='orchards.orchard')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='statistics_images/')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_values', to='orchards.statistic')),
            ],
        ),
        migrations.AddField(
            model_name='statistic',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchards.statistictype'),
        ),
    ]
