version: "3.9"

services:
  web:
    build: .
    container_name: django_app_pets
    volumes:
      - static_volume:/app/static
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn dashboardIOT.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --worker-class gthread
      "
    networks:
      - pets_network
    labels:
      - "project=pets"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: postgres_db_pets
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    labels:
      - "project=pets"
    networks:
      - pets_network
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt_pets
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    labels:
      - "project=pets"
    networks:
      - pets_network

volumes:
  pgdata:
  static_volume:

networks:
  pets_network:
    driver: bridge