# Generated by Django 4.2.19 on 2025-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('next_refill', models.DateTimeField()),
                ('last_refill', models.DateTimeField()),
                ('automatic_start_date', models.DateTimeField()),
                ('automatic_end_date', models.DateTimeField()),
                ('dispense_count', models.IntegerField()),
                ('portion_size', models.IntegerField()),
                ('no_food', models.BooleanField(default=False)),
            ],
        ),
    ]
