# Generated by Django 4.2.19 on 2025-06-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petmachine',
            name='automatic_end_date',
        ),
        migrations.RemoveField(
            model_name='petmachine',
            name='automatic_start_date',
        ),
        migrations.RemoveField(
            model_name='petmachine',
            name='type',
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('schedule_type', models.CharField(choices=[('once', 'Una vez'), ('weekly', 'Semanal'), ('daily', 'Diario')], max_length=20)),
                ('day_of_week', models.CharField(blank=True, choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=9, null=True)),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='pets.petmachine')),
            ],
        ),
    ]
