# Generated by Django 4.2.19 on 2025-06-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_petmachine_automatic_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='minute',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='schedule_type',
            field=models.CharField(choices=[('once', 'Una vez'), ('weekly', 'Semanal'), ('daily', 'Diario')], max_length=20, null=True),
        ),
    ]
