# Generated by Django 4.2.19 on 2025-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_scheduledtask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='schedule_type',
            field=models.CharField(choices=[('Una vez', 'Una vez'), ('Semanal', 'Semanal'), ('Diario', 'Diario')], max_length=20, null=True),
        ),
    ]
