# Generated by Django 4.2.19 on 2025-06-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_scheduledtask_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('Una vez', 'Una vez'), ('Semanal', 'Semanal'), ('Diario', 'Diario')], max_length=20, null=True),
        ),
    ]
