# Generated by Django 4.2.19 on 2025-06-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_scheduledtask_hour_alter_scheduledtask_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábados', 'Sábados'), ('Domingos', 'Domingos')], max_length=9, null=True),
        ),
    ]
