# Generated by Django 4.2.19 on 2025-06-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_scheduledtask_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
