# Generated by Django 4.2.19 on 2025-06-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_scheduledtask_last_executed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmachine',
            name='next_refill',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
