# Generated by Django 4.2.19 on 2025-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_petmachine_next_refill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmachine',
            name='last_refill',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
