# Generated by Django 4.2.19 on 2025-02-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raae_distance', models.FloatField()),
                ('caps_distance', models.FloatField()),
                ('luminaires_distance', models.FloatField()),
                ('batteries_distance', models.FloatField()),
                ('medicines_distance', models.FloatField()),
                ('oils_distance', models.FloatField()),
            ],
        ),
    ]
